[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run prisma:generate",
  "npx tsc"
]

[start]
cmd = "npx prisma db push && npx prisma generate && node dist/main.js"


